### ISSUE TITLE
help！！

### ISSUE THREAD

**Issue by songwenhao123** [Zhaozixiang1228/DIDFuse#2]
你好，在训练的时候出现了这个错误，可以帮忙解决一下吗？
万分感谢
Traceback (most recent call last):
  File "train.py", line 94, in <module>
    ssim = kornia.losses.SSIM(11, reduction='mean')
AttributeError: module 'kornia.losses' has no attribute 'SSIM'

**Comment by liuwukai** [comment]
您好，我也是遇到了这个问题，请问解决了吗？我在网上搜了一下，有的说kornia版本过低，我把版本更新到0.6.10，可结果还是显示AttributeError: module 'kornia.losses' has no attribute 'SSIM'，然后我又搜到SSIM不在losses，而是在metrics中，我又把losses换成metrics，变成ssim = kornia.losses.ssim(img1, img2, 11, 1.0)，又在前面定义了img1和img2，但是在计算损失函数的时候，
mse_loss_VF = 5 * ssim(data_VIS, img_recon_V) + MSELoss(data_VIS, img_recon_V)
        mse_loss_IF = 5 * ssim(data_IR, img_recon_I) + MSELoss(data_IR, img_recon_I)
这两段话显示ssim里的是Tensor类型不可调用，我不知道怎么改动了，就把5 * ssim(data_VIS, img_recon_V)和5 * ssim(data_IR, img_recon_I) 这一点删除了，结果虽然代码能运行了，但是大概训练到30轮左右的时候，loss出现了负数，再往后一直训练基本上出现了大量的负数，我知道可能会出错，但没想到这么离谱，所以请问您还有其他的办法解决一下没，我确实是有点运行不出来，麻烦您了！

**Comment by WenhaoSong-1512** [comment]
你好，这是我很久之前跑的这个程序，我记得我当时是自己定义了一个ssim函数，就可以跑通了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月21日 10:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Zhaozixiang1228/IVIF-DIDFuse] help！！ (Issue #2) |

您好，我也是遇到了这个问题，请问解决了吗？我在网上搜了一下，有的说kornia版本过低，我把版本更新到0.6.10，可结果还是显示AttributeError: module 'kornia.losses' has no attribute 'SSIM'，然后我又搜到SSIM不在losses，而是在metrics中，我又把losses换成metrics，变成ssim = kornia.losses.ssim(img1, img2, 11, 1.0)，又在前面定义了img1和img2，但是在计算损失函数的时候，
mse_loss_VF = 5 * ssim(data_VIS, img_recon_V) + MSELoss(data_VIS, img_recon_V)
mse_loss_IF = 5 * ssim(data_IR, img_recon_I) + MSELoss(data_IR, img_recon_I)
这两段话显示ssim里的是Tensor类型不可调用，我不知道怎么改动了，就把5 * ssim(data_VIS, img_recon_V)和5 * ssim(data_IR, img_recon_I) 这一点删除了，结果虽然代码能运行了，但是大概训练到30轮左右的时候，loss出现了负数，再往后一直训练基本上出现了大量的负数，我知道可能会出错，但没想到这么离谱，所以请问您还有其他的办法解决一下没，我确实是有点运行不出来，麻烦您了！

**Comment by Zhaozixiang1228** [comment]
@songwenhao123 你好，我当时kornia的版本不会很高，应该是一个比较低的版本，但是我现在也记不得了。你试试kornia==0.1.4.post2可以吗？但是我不确定。
@liuwukai 你好，loss可以变为负数，我觉得没有什么问题，只要总损失是下降的就可以，loss是正是负关系不大。

**Comment by liuwukai** [comment]
> @songwenhao123 你好，我当时kornia的版本不会很高，应该是一个比较低的版本，但是我现在也记不得了。你试试kornia==0.1.4.post2可以吗？但是我不确定。 @liuwukai 你好，loss可以变为负数，我觉得没有什么问题，只要总损失是下降的就可以，loss是正是负关系不大。

非常感谢两位大佬的帮助，问题解决了，是因为版本库更新了，函数名称换了，把ssim换成了SSIMLoss，然后那段代码就变成了
ssim = kornia.losses.SSIMLoss( 11,reduction = 'mean')，代码就可以正常运行了。然后运行到40轮的时候也会出现负数，一直到120轮的时候，每轮几乎都会出现一两个负数，我是刚开始接触这，一直以为loss不能出现负数呢，现在又学到了，只要总损失是下降的就可以，loss可以出现负数，哈哈哈，打扰了，非常非常感谢两位的解答和指导！

**Comment by wmx-gtihub** [comment]
谢谢各位大佬！我也是卡在这，看到你们的解答，终于解决了这个问题，跑通了。
